name: Python package

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    permissions:
      checks: write
      contents: read
      pull-requests: write
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Install uv and Python
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.8.18"
          python-version: "3.11"
          enable-cache: true

      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=src" >> $GITHUB_ENV

      - name: Install dependencies (uv)
        run: uv sync --locked --dev

      - name: Install missing stubs
        run: uv pip install types-requests types-jmespath types-toml pandas-stubs types-pytz types-s3transfer types-awscrt

      - name: Ruff check
        run: uv run ruff check --fix -e --no-cache

      - uses: reviewdog/action-suggester@v1
        with:
          tool_name: ruff

      - name: Mypy check
        run: uv run mypy .

  test:
    runs-on: ubuntu-24.04

    strategy:
      matrix:
        PYTHON_VERSION: ['3.11']

    env:
      AIRFLOW_CONN_DATA_LAKE_TEST: '{"conn_type": "aws", "extra": {"endpoint_url": "http://localhost:9090"}}'
      AIRFLOW_CONN_GCP_DATA_LAKE_TEST: '{"conn_type": "google_cloud_platform", "extra": {"key_path": "/.../keyfile.json"}}'
      AIRFLOW_CONN_SFTP_TEST: '{"conn_type": "sftp", "host": "localhost", "port": 2222, "login": "test_user", "password": "pass"}'
      AWS_ACCESS_KEY_ID: AKIAIOSFODNN7EXAMPLE
      AWS_SECRET_ACCESS_KEY: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
      AWS_DEFAULT_REGION: us-east-1
      TEST_BUCKET: data_lake
      S3_ENDPOINT_URL: http://localhost:9090
      AWS_S3_ADDRESSING_STYLE: path
      AWS_USE_EXPECT_HEADER: false

    steps:
      - uses: actions/checkout@v4

      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=src" >> $GITHUB_ENV

      - name: Install uv and Python
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.8.18"
          python-version: ${{ matrix.PYTHON_VERSION }}
          enable-cache: true

      - name: Install dependencies (uv)
        run: uv sync --locked --dev

      - name: Initialize database
        run: uv run airflow db init

      - name: Start S3/Mock server
        run: docker run -d --name test-s3mock --rm -p 9090:9090 -e initialBuckets=data_lake -e debug=true -t adobe/s3mock

      - name: Start SFTP server
        run: docker start test-sftp
        # run: docker run -p 2222:22 -d atmoz/sftp test_user:pass:::root_folder

      - name: Run tests with pytest
        run: >
          uv run pytest  --tb=short tests/
          --doctest-modules
          --junitxml=junit/test-results.xml
          --cov=src
          --cov-report=xml
          --cov-report=html
      - name: Stop S3/Mock server
        if: always()
        run: docker stop test-s3mock || true
      - name: Stop SFTP server
        if: always()
        run: docker stop test-sftp || true
